from __future__ import annotations

from ..common import *


STATUS_LINES = (
    "[ok] validated nested AGENTS docs",
    "[ok] validated mechanics skeleton",
    "[ok] validated questbook quest-store surfaces",
    "[ok] validated KAG registry schema surface",
    "[ok] validated bridge retrieval surface schema",
    "[ok] validated bridge envelope schema",
    "[ok] validated counterpart edge surface schema",
    "[ok] validated counterpart federation exposure review manifest schema",
    "[ok] validated counterpart federation exposure review schema",
    "[ok] validated counterpart consumer contract schema",
    "[ok] validated reasoning handoff guardrail schema",
    "[ok] validated projection health receipt schema",
    "[ok] validated regrounding ticket schema",
    "[ok] validated technique lift manifest schema",
    "[ok] validated technique lift pack schema",
    "[ok] validated ToS text chunk map manifest schema",
    "[ok] validated ToS text chunk map schema",
    "[ok] validated ToS retrieval axis manifest schema",
    "[ok] validated ToS retrieval axis pack schema",
    "[ok] validated ToS Zarathustra route pack manifest schema",
    "[ok] validated ToS Zarathustra route pack schema",
    "[ok] validated ToS Zarathustra route retrieval pack manifest schema",
    "[ok] validated ToS Zarathustra route retrieval pack schema",
    "[ok] validated reasoning handoff pack manifest schema",
    "[ok] validated reasoning handoff pack schema",
    "[ok] validated return regrounding manifest schema",
    "[ok] validated return regrounding pack schema",
    "[ok] validated KAG maturity governance manifest schema",
    "[ok] validated KAG maturity governance pack schema",
    "[ok] validated source-owned export dependency manifest schema",
    "[ok] validated federation export registry manifest schema",
    "[ok] validated federation export registry schema",
    "[ok] validated federation KAG export schema",
    "[ok] validated federation spine manifest schema",
    "[ok] validated federation spine schema",
    "[ok] validated cross-source node projection manifest schema",
    "[ok] validated cross-source node projection schema",
    "[ok] validated tiny consumer bundle manifest schema",
    "[ok] validated tiny consumer bundle schema",
    "[ok] validated manifests/kag_registry.json",
    f"[ok] validated {TECHNIQUE_LIFT_MANIFEST_REF}",
    f"[ok] validated {TOS_TEXT_CHUNK_MAP_MANIFEST_REF}",
    f"[ok] validated {TOS_RETRIEVAL_AXIS_MANIFEST_REF}",
    f"[ok] validated {TOS_ZARATHUSTRA_ROUTE_PACK_MANIFEST_REF}",
    f"[ok] validated {TOS_ZARATHUSTRA_ROUTE_RETRIEVAL_PACK_MANIFEST_REF}",
    f"[ok] validated {REASONING_HANDOFF_MANIFEST_REF}",
    f"[ok] validated {RETURN_REGROUNDING_MANIFEST_REF}",
    f"[ok] validated {KAG_MATURITY_GOVERNANCE_MANIFEST_REF}",
    f"[ok] validated {SOURCE_OWNED_EXPORT_DEPENDENCIES_MANIFEST_REF}",
    f"[ok] validated {FEDERATION_EXPORT_REGISTRY_MANIFEST_REF}",
    f"[ok] validated {FEDERATION_SPINE_MANIFEST_REF}",
    f"[ok] validated {CROSS_SOURCE_NODE_PROJECTION_MANIFEST_REF}",
    f"[ok] validated {COUNTERPART_FEDERATION_EXPOSURE_REVIEW_MANIFEST_REF}",
    "[ok] validated mechanics/boundary-bridge/parts/tiny-consumer-bundle/manifests/tiny_consumer_bundle.json",
    "[ok] validated generated registry outputs are up to date",
    "[ok] validated generated technique lift pack outputs are up to date",
    "[ok] validated generated ToS text chunk map outputs are up to date",
    "[ok] validated generated ToS retrieval axis pack outputs are up to date",
    "[ok] validated generated ToS Zarathustra route pack outputs are up to date",
    "[ok] validated generated ToS Zarathustra route retrieval pack outputs are up to date",
    "[ok] validated generated reasoning handoff pack outputs are up to date",
    "[ok] validated generated federation export registry outputs are up to date",
    "[ok] validated generated return regrounding pack outputs are up to date",
    "[ok] validated generated KAG maturity governance pack outputs are up to date",
    "[ok] validated generated federation spine outputs are up to date",
    "[ok] validated generated cross-source node projection outputs are up to date",
    "[ok] validated generated counterpart federation exposure review outputs are up to date",
    "[ok] validated generated tiny consumer bundle outputs are up to date",
    "[ok] validated generated technique lift pack structure",
    "[ok] validated generated ToS text chunk map structure",
    "[ok] validated generated ToS retrieval axis pack structure",
    "[ok] validated generated ToS Zarathustra route pack structure",
    "[ok] validated generated ToS Zarathustra route retrieval pack structure",
    "[ok] validated generated reasoning handoff pack structure",
    "[ok] validated generated federation export registry structure",
    "[ok] validated generated return regrounding pack structure",
    "[ok] validated generated KAG maturity governance pack structure",
    "[ok] validated generated federation spine structure",
    "[ok] validated generated cross-source node projection structure",
    "[ok] validated generated counterpart federation exposure review structure",
    "[ok] validated generated tiny consumer bundle structure",
    "[ok] validated antifragility projection-health adjunct surfaces",
    "[ok] validated bridge retrieval example",
    "[ok] validated bridge envelope example",
    "[ok] validated counterpart edge example",
    "[ok] validated counterpart consumer contract example",
    "[ok] validated ToS text chunk map example",
    "[ok] validated ToS retrieval axis example",
    "[ok] validated ToS Zarathustra route pack example",
    "[ok] validated ToS Zarathustra route retrieval pack example",
    "[ok] validated reasoning handoff guardrail example",
    "[ok] validated return regrounding example",
    "[ok] validated KAG maturity governance example",
    "[ok] validated federation export registry example",
    "[ok] validated federation KAG export example",
)

TAIL_STATUS_LINES = (
    "[ok] validated memo source-owned export consumer boundary doc",
    "[ok] validated cross-source node projection example",
    "[ok] validated counterpart federation exposure review example",
    "[ok] validated tiny consumer bundle example",
)


def print_success_status() -> None:
    for line in STATUS_LINES:
        print(line)
    if AOA_MEMO_ROOT.exists():
        print("[ok] validated optional aoa-memo source-owned export readiness")
    for line in TAIL_STATUS_LINES:
        print(line)
